# Generated by Django 5.0.1 on 2024-02-14 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0003_alter_lesson_link_subscription'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subscription',
            name='is_subscribed',
        ),
        migrations.AddField(
            model_name='course',
            name='link',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='Ссылка'),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='link',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='Ссылка'),
        ),
    ]
